/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.Sales;

import controllers.SaleController;
import controllers.ShoppingCartController;
import java.awt.Color;
import java.awt.Font;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import model.Product;
import model.Sale;
import model.ShoppingCart;
import model.User;
import view.ManagmentProducts.ManagmentProducts;
import view.user.ValidationMembership;

/**
 *
 * @author joanp
 */
public class CartDetails extends javax.swing.JInternalFrame {

    private final ManagmentProducts view;
    private final User user;
    private final ShoppingCartController cartController;
    private final SaleController salesController;
    private final ShoppingCart cart;
    private ValidationMembership viewValidation;

    /**
     * Creates new form CashRegister
     *
     * @param view
     * @param user
     * @param cart
     */
    public CartDetails(ManagmentProducts view, User user, ShoppingCart cart) {
        initComponents();
        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
        this.user = user;
        this.cart = cart;
        this.view = view;
        cartController = new ShoppingCartController(cart);
        salesController = new SaleController();
        fillProductsTable();
        setTotal();

    }

    private void validateScreen() {
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice[] devices = ge.getScreenDevices();

        if (devices.length <= 1) {
            JOptionPane.showMessageDialog(null, "No hay una segunda pantalla disponible");
        } else {
            viewValidation.showCartInformation(cart);
        }
    }

    private void tableCustomization() {
        productsTable.getTableHeader().setFont(new Font("Rockwell", Font.BOLD, 14));
        productsTable.getTableHeader().setOpaque(true);
        productsTable.getTableHeader().setBackground(new Color(255, 255, 255));
        productsTable.getTableHeader().setForeground(new Color(0, 0, 0));
    }

    private void fillProductsTable() {
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        ArrayList<Product> products = cart.getProducts();
        model.setColumnIdentifiers(new Object[]{
            "#", "Nombre", "Categoría", "Precio"
        });

        productsTable.setModel(model);
        tableCustomization();

        for (int i = 0; i < products.size(); i++) {
            Product prod = (Product) products.get(i);
            model.addRow(new Object[]{
                prod.getId(),
                prod.getName(),
                prod.getCategory(),
                prod.getPrice()
            });
        }

    }

    private void setTotal() {
        lblTotal.setText(String.valueOf(cart.getTotal()));
    }

    private boolean hasEmptyFields() {
        return (cbxPaymentMethod.getSelectedIndex() == 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        productsTable = new javax.swing.JTable();
        btnSell = new javax.swing.JButton();
        btnDeleteProduct = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        btnDebt = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cbxPaymentMethod = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Total:");

        productsTable.setBackground(new java.awt.Color(255, 255, 255));
        productsTable.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        productsTable.setForeground(new java.awt.Color(0, 0, 0));
        productsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        productsTable.setSelectionBackground(new java.awt.Color(254, 205, 77));
        jScrollPane1.setViewportView(productsTable);

        btnSell.setBackground(new java.awt.Color(254, 205, 77));
        btnSell.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        btnSell.setForeground(new java.awt.Color(0, 0, 0));
        btnSell.setText("Finalizar venta");
        btnSell.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellActionPerformed(evt);
            }
        });

        btnDeleteProduct.setBackground(new java.awt.Color(254, 205, 77));
        btnDeleteProduct.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        btnDeleteProduct.setForeground(new java.awt.Color(0, 0, 0));
        btnDeleteProduct.setText("Quitar producto");
        btnDeleteProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteProductActionPerformed(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("50.000");

        btnDebt.setBackground(new java.awt.Color(254, 205, 77));
        btnDebt.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        btnDebt.setForeground(new java.awt.Color(0, 0, 0));
        btnDebt.setText("Fiar");
        btnDebt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDebt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDebtActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Metodo de pago:");

        cbxPaymentMethod.setBackground(new java.awt.Color(255, 255, 255));
        cbxPaymentMethod.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        cbxPaymentMethod.setForeground(new java.awt.Color(0, 0, 0));
        cbxPaymentMethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción", "Efectivo", "Nequi", "Daviplata" }));
        cbxPaymentMethod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPaymentMethodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(60, 60, 60)
                                .addComponent(cbxPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(382, 382, 382)
                                .addComponent(jLabel1)
                                .addGap(51, 51, 51)
                                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(btnDeleteProduct)
                        .addGap(200, 200, 200)
                        .addComponent(btnDebt)
                        .addGap(200, 200, 200)
                        .addComponent(btnSell)))
                .addContainerGap(382, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(cbxPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(lblTotal)))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteProduct)
                    .addComponent(btnDebt)
                    .addComponent(btnSell))
                .addContainerGap(239, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellActionPerformed

        if (hasEmptyFields()) {
            JOptionPane.showMessageDialog(null, "Seleccione el metodo de pago antes de continuar");
            return;
        }

        int answer = JOptionPane.showConfirmDialog(null, "¿Está seguro de realizar la venta?", "Advertencia", JOptionPane.YES_NO_OPTION);

        if (answer == 0) {
            for (int i = 0; i < cart.getProducts().size(); i++) {
                Product product = cart.getProducts().get(i);
                String payment = cbxPaymentMethod.getSelectedItem().toString();
                Sale sale = new Sale(product, user, payment);
                salesController.insertSale(sale);
            }
            JOptionPane.showMessageDialog(null, "Venta realizada correctamente");
            view.fillProductsTable();
            cart.getProducts().clear();
            viewValidation.hideCartPanel();
            viewValidation.showLblThxs();
            this.dispose();
        }
    }//GEN-LAST:event_btnSellActionPerformed

    private void btnDeleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteProductActionPerformed

        int selection = productsTable.getSelectedRow();

        if (selection < 0) {
            JOptionPane.showMessageDialog(null, "Seleccione un producto antes de continuar", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int id = Integer.parseInt(productsTable.getValueAt(selection, 0).toString());

        cartController.removeFromCart(id);
        JOptionPane.showMessageDialog(null, "El producto ha sido eliminado correctamente");
        fillProductsTable();
        view.fillProductsTable();
        setTotal();

        if (cart.getProducts().isEmpty()) {
            this.dispose();
        }
    }//GEN-LAST:event_btnDeleteProductActionPerformed

    private void btnDebtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDebtActionPerformed

        if (hasEmptyFields()) {
            JOptionPane.showMessageDialog(null, "Seleccione el metodo de pago antes de continuar");
            return;
        }

        String paymentMethod = cbxPaymentMethod.getSelectedItem().toString();

        this.dispose();
        new SaleLoan(view, cart, user, paymentMethod).setVisible(true);
    }//GEN-LAST:event_btnDebtActionPerformed

    private void cbxPaymentMethodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPaymentMethodActionPerformed
    }//GEN-LAST:event_cbxPaymentMethodActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDebt;
    private javax.swing.JButton btnDeleteProduct;
    private javax.swing.JButton btnSell;
    private javax.swing.JComboBox<String> cbxPaymentMethod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable productsTable;
    // End of variables declaration//GEN-END:variables
}
