/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.ManagmentCustomers;

import controllers.CustomerController;
import enums.MembershipType;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import model.Customer;
import model.Membership;
import model.User;
import view.main.MainView;

/**
 *
 * @author joanp
 */
public class MembershipDetails extends javax.swing.JInternalFrame {

    private final Customer customer;
    private final CustomerController controller;
    private final ManagmentCustomers view;
    private final MainView viewM;
    private final User user;

    /**
     * Creates new form MembershipDetails
     *
     * @param customer
     * @param view
     * @param user
     * @param viewM
     */
    public MembershipDetails(Customer customer, ManagmentCustomers view, User user, MainView viewM) {
        initComponents();
        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
        controller = new CustomerController();
        this.customer = customer;
        this.view = view;
        this.user = user;
        this.viewM = viewM;
        setCbxMembership();
        showMembershipData();
    }

    private void showMembershipData() {
        txtStartDate.setText(String.valueOf(customer.getMembership().getStartDate()));
        txtEndDate.setText(String.valueOf(customer.getMembership().getEndDate()));
        cbxPaymentMethod.setSelectedItem(customer.getMembership().getPaymentMethod());

        MembershipType customerMembershipType = customer.getMembership().getType();

        for (int i = 0; i < cbxMembership.getItemCount(); i++) {
            if (cbxMembership.getItemAt(i).equals(customerMembershipType.getName())) {
                cbxMembership.setSelectedIndex(i);
                break;
            }
        }
    }

    private void setCbxMembership() {
        for (MembershipType type : MembershipType.values()) {
            cbxMembership.addItem(type.getName());
        }
    }

    private boolean validateEmptyFields() {
        return (txtStartDate.getText().isEmpty() || txtEndDate.getText().isEmpty() || cbxMembership.getSelectedIndex() == 0
                || cbxPaymentMethod.getSelectedIndex() == 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtStartDate = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        txtEndDate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbxMembership = new javax.swing.JComboBox<>();
        btnRenewMembership = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cbxPaymentMethod = new javax.swing.JComboBox<>();
        btnEdit = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fecha inicio:");

        jSeparator2.setForeground(new java.awt.Color(254, 205, 77));

        txtStartDate.setBackground(new java.awt.Color(0, 0, 0));
        txtStartDate.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        txtStartDate.setForeground(new java.awt.Color(255, 255, 255));
        txtStartDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtStartDate.setBorder(null);
        txtStartDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStartDateKeyTyped(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(254, 205, 77));

        txtEndDate.setBackground(new java.awt.Color(0, 0, 0));
        txtEndDate.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        txtEndDate.setForeground(new java.awt.Color(255, 255, 255));
        txtEndDate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEndDate.setBorder(null);
        txtEndDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEndDateKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha fin:");

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tipo membresia:");

        cbxMembership.setBackground(new java.awt.Color(255, 255, 255));
        cbxMembership.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        cbxMembership.setForeground(new java.awt.Color(0, 0, 0));
        cbxMembership.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción" }));

        btnRenewMembership.setBackground(new java.awt.Color(254, 205, 77));
        btnRenewMembership.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btnRenewMembership.setForeground(new java.awt.Color(0, 0, 0));
        btnRenewMembership.setText("Renovar Membresía");
        btnRenewMembership.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRenewMembershipActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Metodo de pago:");

        cbxPaymentMethod.setBackground(new java.awt.Color(255, 255, 255));
        cbxPaymentMethod.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        cbxPaymentMethod.setForeground(new java.awt.Color(0, 0, 0));
        cbxPaymentMethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción", "Efectivo", "Nequi", "Daviplata" }));

        btnEdit.setBackground(new java.awt.Color(254, 205, 77));
        btnEdit.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(0, 0, 0));
        btnEdit.setText("Editar");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(97, 97, 97)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxMembership, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRenewMembership)
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(19, 19, 19)
                                    .addComponent(txtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(19, 19, 19)
                                    .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(584, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbxPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbxMembership, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRenewMembership)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(251, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtStartDateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStartDateKeyTyped

    }//GEN-LAST:event_txtStartDateKeyTyped

    private void txtEndDateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEndDateKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEndDateKeyTyped

    private void btnRenewMembershipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRenewMembershipActionPerformed
        if (cbxMembership.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Seleccione un tipo de membresía");
            return;
        }

        String selectedMembershipName = cbxMembership.getSelectedItem().toString();
        MembershipType membershipType = null;
        String paymentMethod = cbxPaymentMethod.getSelectedItem().toString();
        

        for (MembershipType type : MembershipType.values()) {
            if (type.getName().equals(selectedMembershipName)) {
                membershipType = type;
                break;
            }
        }

        Membership membership = new Membership(membershipType, user, paymentMethod);
        controller.renewMembership(customer.getCedula(), membership);

        JOptionPane.showMessageDialog(null, "Membresía renovada correctamente");
        view.fillCustomersTable();
        this.dispose();
    }//GEN-LAST:event_btnRenewMembershipActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if (validateEmptyFields()) {
            JOptionPane.showMessageDialog(null, "Llene todos los campos");
            return;
        }

        LocalDate startDate = LocalDate.parse(txtStartDate.getText());
        LocalDate endDate = LocalDate.parse(txtEndDate.getText());
        String selectedMembershipName = cbxMembership.getSelectedItem().toString();
        MembershipType membershipType = null;
        String paymentMethod = cbxPaymentMethod.getSelectedItem().toString();

        for (MembershipType type : MembershipType.values()) {
            if (type.getName().equals(selectedMembershipName)) {
                membershipType = type;
                break;
            }
        }

        Membership membership = new Membership(membershipType, startDate, endDate, user, paymentMethod);
        controller.editMembership(customer.getCedula(), membership);

        JOptionPane.showMessageDialog(null, "Membresía editada");
        view.fillCustomersTable();
        this.dispose();

    }//GEN-LAST:event_btnEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRenewMembership;
    private javax.swing.JComboBox<String> cbxMembership;
    private javax.swing.JComboBox<String> cbxPaymentMethod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField txtEndDate;
    private javax.swing.JTextField txtStartDate;
    // End of variables declaration//GEN-END:variables
}
