/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.ManagmentCustomers;

import controllers.CustomerController;
import controllers.CustomerDayController;
import enums.MembershipType;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import model.Customer;
import model.EmergencyContact;
import model.Membership;
import model.User;
import placeHolder.PlaceHolder;
import view.main.MainView;

/**
 *
 * @author joanp
 */
public class RegisterCustomer extends javax.swing.JInternalFrame {

    private final CustomerDayController controllerday;
    private final CustomerController controller;
    private final ManagmentCustomers view;
    private final MainView viewM;
    private final User user;

    /**
     * Creates new form RegisterUser
     *
     * @param view
     * @param user
     * @param viewM
     */
    public RegisterCustomer(ManagmentCustomers view, User user, MainView viewM) {
        initComponents();
        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
        controller = new CustomerController();
        controllerday = new CustomerDayController();
        this.user = user;
        this.view = view;
        this.viewM = viewM;
        hideAlert();
        setCbxMembership();
        showPlaceHolders();
    }

    private void noEnabledFields() {
        txtBirthDate.setEnabled(false);
        txtContactFullname.setEnabled(false);
        txtContactPhoneNumber.setEnabled(false);
        txtHealthInformation.setEnabled(false);
    }

    private void enabledFields() {
        txtBirthDate.setEnabled(true);
        txtContactFullname.setEnabled(true);
        txtContactPhoneNumber.setEnabled(true);
        txtHealthInformation.setEnabled(true);
    }

    private LocalDate parseDate(String dateString) {
        DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        return LocalDate.parse(dateString, dateFormatter);
    }

    private void setCbxMembership() {
        for (MembershipType type : MembershipType.values()) {
            cbxMembership.addItem(type.getName());
        }
    }

    private boolean hasEmptyFields() {
        return (txtCedula.getText().isEmpty() || txtCustomerFullname.getText().isEmpty() || txtCustomerPhoneNumber.getText().length() < 12
                || txtBirthDate.getText().length() < 10 || txtContactFullname.getText().isEmpty() || txtContactPhoneNumber.getText().length() < 12 || txtHealthInformation.getText().isEmpty()
                || cbxMembership.getSelectedIndex() == 0 || cbxPaymentMethod.getSelectedIndex() == 0);
    }

    private boolean hasEmptyFieldsCustomerDay() {
        return (txtCedula.getText().isEmpty() || txtCustomerFullname.getText().isEmpty() || txtCustomerPhoneNumber.getText().length() < 12
                || cbxMembership.getSelectedIndex() == 0 || cbxPaymentMethod.getSelectedIndex() == 0);
    }

    @SuppressWarnings("ResultOfObjectAllocationIgnored")
    private void showPlaceHolders() {
        new PlaceHolder("Ingrese una cédula", txtCedula);
        new PlaceHolder("Ingrese un nombre", txtCustomerFullname);
        new PlaceHolder("Ingrese un nombre", txtContactFullname);
        new PlaceHolder("EPS / Patologias ", txtHealthInformation);
    }

    private void showAlert() {
        lblAlert.setVisible(true);
    }

    private void hideAlert() {
        lblAlert.setVisible(false);
    }

    private void validateFields() {
        String cedula = txtCedula.getText().trim();
        Customer customer = controller.selectCustomer(cedula);

        boolean enableBtnRegisterCustomer = true;

        if (!cedula.isEmpty() && customer != null) {
            lblAlert.setText("Cédula ya registrada");
            showAlert();
            enableBtnRegisterCustomer = false;
        } else {
            hideAlert();
        }

        btnRegisterCustomer.setEnabled(enableBtnRegisterCustomer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtCustomerFullname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        txtBirthDate = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        txtCedula = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        txtContactFullname = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtHealthInformation = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        cbxMembership = new javax.swing.JComboBox<>();
        btnRegisterCustomer = new javax.swing.JButton();
        lblAlert = new javax.swing.JLabel();
        txtContactPhoneNumber = new javax.swing.JFormattedTextField();
        txtCustomerPhoneNumber = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        cbxPaymentMethod = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre completo:");

        jSeparator1.setForeground(new java.awt.Color(254, 205, 77));

        txtCustomerFullname.setBackground(new java.awt.Color(0, 0, 0));
        txtCustomerFullname.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        txtCustomerFullname.setForeground(new java.awt.Color(255, 255, 255));
        txtCustomerFullname.setBorder(null);
        txtCustomerFullname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCustomerFullnameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCustomerFullnameKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Numero de teléfono:");

        jSeparator2.setForeground(new java.awt.Color(254, 205, 77));

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fecha de nacimiento:");

        jSeparator3.setForeground(new java.awt.Color(254, 205, 77));

        txtBirthDate.setBackground(new java.awt.Color(0, 0, 0));
        txtBirthDate.setBorder(null);
        txtBirthDate.setForeground(new java.awt.Color(255, 255, 255));
        try {
            txtBirthDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtBirthDate.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cédula:");

        jSeparator6.setForeground(new java.awt.Color(254, 205, 77));

        txtCedula.setBackground(new java.awt.Color(0, 0, 0));
        txtCedula.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        txtCedula.setForeground(new java.awt.Color(255, 255, 255));
        txtCedula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCedula.setBorder(null);
        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCedulaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Contacto de emergencia:");

        jSeparator7.setForeground(new java.awt.Color(254, 205, 77));

        jSeparator8.setForeground(new java.awt.Color(254, 205, 77));

        txtContactFullname.setBackground(new java.awt.Color(0, 0, 0));
        txtContactFullname.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        txtContactFullname.setForeground(new java.awt.Color(255, 255, 255));
        txtContactFullname.setBorder(null);
        txtContactFullname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtContactFullnameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContactFullnameKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Telefono");

        jLabel9.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nombre");

        txtHealthInformation.setBackground(new java.awt.Color(0, 0, 0));
        txtHealthInformation.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        txtHealthInformation.setForeground(new java.awt.Color(255, 255, 255));
        txtHealthInformation.setBorder(null);
        txtHealthInformation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHealthInformationKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Información médica:");

        jSeparator9.setForeground(new java.awt.Color(254, 205, 77));

        jLabel11.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Membresía:");

        cbxMembership.setBackground(new java.awt.Color(255, 255, 255));
        cbxMembership.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        cbxMembership.setForeground(new java.awt.Color(0, 0, 0));
        cbxMembership.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción" }));
        cbxMembership.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxMembershipItemStateChanged(evt);
            }
        });

        btnRegisterCustomer.setBackground(new java.awt.Color(254, 205, 77));
        btnRegisterCustomer.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        btnRegisterCustomer.setForeground(new java.awt.Color(0, 0, 0));
        btnRegisterCustomer.setText("Guardar");
        btnRegisterCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegisterCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterCustomerActionPerformed(evt);
            }
        });

        lblAlert.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        lblAlert.setForeground(new java.awt.Color(204, 0, 0));
        lblAlert.setText("jLabel4");

        txtContactPhoneNumber.setBackground(new java.awt.Color(0, 0, 0));
        txtContactPhoneNumber.setBorder(null);
        txtContactPhoneNumber.setForeground(new java.awt.Color(255, 255, 255));
        try {
            txtContactPhoneNumber.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtContactPhoneNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtContactPhoneNumber.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N

        txtCustomerPhoneNumber.setBackground(new java.awt.Color(0, 0, 0));
        txtCustomerPhoneNumber.setBorder(null);
        txtCustomerPhoneNumber.setForeground(new java.awt.Color(255, 255, 255));
        try {
            txtCustomerPhoneNumber.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCustomerPhoneNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCustomerPhoneNumber.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Metodo de pago:");

        cbxPaymentMethod.setBackground(new java.awt.Color(255, 255, 255));
        cbxPaymentMethod.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        cbxPaymentMethod.setForeground(new java.awt.Color(0, 0, 0));
        cbxPaymentMethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción", "Efectivo", "Nequi", "Daviplata" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(460, 460, 460)
                        .addComponent(btnRegisterCustomer)
                        .addGap(195, 195, 195)
                        .addComponent(lblAlert))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(60, 60, 60)
                                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(84, 84, 84)
                                            .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(81, 81, 81)
                                            .addComponent(jLabel10)
                                            .addGap(57, 57, 57)
                                            .addComponent(txtHealthInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(314, 314, 314)
                                            .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jSeparator3)
                                                    .addComponent(txtBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(46, 46, 46)
                                                .addComponent(jLabel7)
                                                .addGap(60, 60, 60)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jSeparator7)
                                                    .addComponent(txtContactPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(48, 48, 48)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(txtContactFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(167, 167, 167)
                                                .addComponent(jLabel9)
                                                .addGap(91, 91, 91))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(60, 60, 60)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(9, 9, 9)
                                                .addComponent(txtCustomerFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(60, 60, 60)
                                        .addComponent(jLabel2)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(60, 60, 60)
                                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(90, 90, 90)
                                                .addComponent(txtCustomerPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jLabel11)
                                .addGap(60, 60, 60)
                                .addComponent(cbxMembership, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100)
                                .addComponent(jLabel4)
                                .addGap(60, 60, 60)
                                .addComponent(cbxPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(326, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtCustomerFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(txtCustomerPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(txtContactPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtContactFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtBirthDate, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtHealthInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbxMembership, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cbxPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegisterCustomer)
                    .addComponent(lblAlert))
                .addContainerGap(203, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyTyped
        String cedula = txtCedula.getText();
        char c = evt.getKeyChar();

        if (!Character.isDigit(c) || cedula.length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCedulaKeyTyped

    private void btnRegisterCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterCustomerActionPerformed
        String selectedMembershipName = cbxMembership.getSelectedItem().toString();
        MembershipType membershipType = getMembershipType(selectedMembershipName);

        if (membershipType == null) {
            JOptionPane.showMessageDialog(null, "Escoja un tipo de membresía");
            return;
        }

        // Validate input fields
        if (hasEmptyFields()) {
            String alertMessage = "";
            if (membershipType != MembershipType.DIA) {
                alertMessage = "Ingrese todos los datos";
            } else if (hasEmptyFieldsCustomerDay()) {
                alertMessage = "Ingrese todos los datos para la clase";
            }

            if (!alertMessage.isEmpty()) {
                lblAlert.setText(alertMessage);
                showAlert();
                return;
            }
        }

// Resto del código después de la validación de campos vacíos
// Emergency contact data
        String contactFullname = txtContactFullname.getText();
        String contactPhoneNumber = txtContactPhoneNumber.getText().trim();

        EmergencyContact emergencyContact = new EmergencyContact(contactFullname, contactPhoneNumber);

// Membership data
        String paymentMethod = cbxPaymentMethod.getSelectedItem().toString();

// Customer data
        String cedula = txtCedula.getText().trim();
        String fullname = txtCustomerFullname.getText();
        String phoneNumber = txtCustomerPhoneNumber.getText().trim();
        String healthInformation = txtHealthInformation.getText();

// Process customer registration based on membership type
        if (membershipType == MembershipType.DIA) {
            registerCustomerForDayMembership(fullname, phoneNumber, cedula, paymentMethod);
        } else {

            LocalDate birthDate = parseDate(txtBirthDate.getText());
            registerRegularCustomer(birthDate, emergencyContact, membershipType, healthInformation, fullname, phoneNumber, cedula, paymentMethod);
        }

    }

    // Helper methods
    private MembershipType getMembershipType(String selectedMembershipName) {
        for (MembershipType type : MembershipType.values()) {
            if (type.getName().equals(selectedMembershipName)) {
                return type;
            }
        }
        return null;
    }

    private void registerCustomerForDayMembership(String fullname, String phoneNumber, String cedula, String paymentMethod) {
        Customer customerDay = new Customer(fullname, phoneNumber, cedula, new Membership(MembershipType.DIA, user, paymentMethod));
        controllerday.insertCustomerDay(customerDay);
        JOptionPane.showMessageDialog(null, "Cliente registrado correctamente");
        view.fillCustomersTable();
        this.dispose();
        viewM.openManagmentCustomersView();
    }

    private void registerRegularCustomer(LocalDate birthDate, EmergencyContact emergencyContact, MembershipType membershipType,
            String healthInformation, String fullname, String phoneNumber, String cedula, String paymentMethod) {
        Customer customer = new Customer(birthDate, emergencyContact, new Membership(membershipType, user, paymentMethod), healthInformation, fullname, phoneNumber, cedula);
        controller.insertCustomer(customer);
        JOptionPane.showMessageDialog(null, "Cliente registrado correctamente");
        view.fillCustomersTable();
        this.dispose();
        viewM.openManagmentCustomersView();

    }//GEN-LAST:event_btnRegisterCustomerActionPerformed

    private void txtHealthInformationKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHealthInformationKeyReleased
        validateFields();
    }//GEN-LAST:event_txtHealthInformationKeyReleased

    private void txtContactFullnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactFullnameKeyReleased
        validateFields();
    }//GEN-LAST:event_txtContactFullnameKeyReleased

    private void txtCustomerFullnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerFullnameKeyReleased
        validateFields();
    }//GEN-LAST:event_txtCustomerFullnameKeyReleased

    private void txtCedulaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyReleased
        validateFields();
    }//GEN-LAST:event_txtCedulaKeyReleased

    private void txtCustomerFullnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerFullnameKeyTyped
        String fullname = txtCustomerFullname.getText();
        char c = evt.getKeyChar();

        if (Character.isDigit(c) || fullname.length() == 100) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCustomerFullnameKeyTyped

    private void txtContactFullnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactFullnameKeyTyped
        String fullname = txtContactFullname.getText();
        char c = evt.getKeyChar();

        if (Character.isDigit(c) || fullname.length() == 100) {
            evt.consume();
        }
    }//GEN-LAST:event_txtContactFullnameKeyTyped

    private void cbxMembershipItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxMembershipItemStateChanged
        String selectedMembershipName = cbxMembership.getSelectedItem().toString();
        MembershipType membershipType = null;

        for (MembershipType type : MembershipType.values()) {
            if (type.getName().equals(selectedMembershipName)) {
                membershipType = type;
                break;
            }
        }

        if (membershipType == MembershipType.DIA) {
            noEnabledFields();
        } else {
            enabledFields();
        }

    }//GEN-LAST:event_cbxMembershipItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegisterCustomer;
    private javax.swing.JComboBox<String> cbxMembership;
    private javax.swing.JComboBox<String> cbxPaymentMethod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblAlert;
    private javax.swing.JFormattedTextField txtBirthDate;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtContactFullname;
    private javax.swing.JFormattedTextField txtContactPhoneNumber;
    private javax.swing.JTextField txtCustomerFullname;
    private javax.swing.JFormattedTextField txtCustomerPhoneNumber;
    private javax.swing.JTextField txtHealthInformation;
    // End of variables declaration//GEN-END:variables
}
