/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.trainers;

import controllers.TrainerController;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Trainer;
import model.User;
import view.main.MainView;

/**
 *
 * @author joanp
 */
public class ManagmentTrainer extends javax.swing.JInternalFrame {

    private final TrainerController controller;

    private TableRowSorter<DefaultTableModel> sorter;
    private final MainView view;

    /**
     * Creates new form ManagmentTrainer
     *
     * @param view
     */
    public ManagmentTrainer(MainView view) {
        initComponents();
        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI bui = (BasicInternalFrameUI) this.getUI();
        bui.setNorthPane(null);
        controller = new TrainerController();
        this.view = view;
        fillTrainersTable();
    }

    private void tableCustomization() {
        trainersTable.getTableHeader().setFont(new Font("Rockwell", Font.BOLD, 14));
        trainersTable.getTableHeader().setOpaque(true);
        trainersTable.getTableHeader().setBackground(new Color(255, 255, 255));
        trainersTable.getTableHeader().setForeground(new Color(0, 0, 0));
    }

    public final void fillTrainersTable() {
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        ArrayList<Object> trainers = controller.listTrainers();
        model.setColumnIdentifiers(new Object[]{
            "Cédula", "Nombre completo", "Teléfono", "Contraseña"
        });

        trainersTable.setModel(model);
        tableCustomization();

        trainersTable.setAutoCreateRowSorter(true);
        sorter = new TableRowSorter<>(model);
        trainersTable.setRowSorter(sorter);

        for (int i = 0; i < trainers.size(); i++) {
            Trainer trn = (Trainer) trainers.get(i);
            model.addRow(new Object[]{
                trn.getCedula(),
                trn.getFullname(),
                trn.getPhoneNumber(),
                trn.getPassword()
            });
        }
    }

    private void filter() {
        sorter.setRowFilter(RowFilter.regexFilter(txtFilter.getText()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtFilter = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        trainersTable = new javax.swing.JTable();
        btnUpdateTrainer = new javax.swing.JButton();
        btnDeleteTrainer = new javax.swing.JButton();
        btnRegisterTrainer = new javax.swing.JButton();

        mainPanel.setBackground(new java.awt.Color(0, 0, 0));
        mainPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mainPanelMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buscar:");

        jSeparator1.setForeground(new java.awt.Color(254, 205, 77));

        txtFilter.setBackground(new java.awt.Color(0, 0, 0));
        txtFilter.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        txtFilter.setForeground(new java.awt.Color(255, 255, 255));
        txtFilter.setBorder(null);
        txtFilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFilterKeyReleased(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setForeground(new java.awt.Color(254, 205, 77));

        trainersTable.setBackground(new java.awt.Color(255, 255, 255));
        trainersTable.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        trainersTable.setForeground(new java.awt.Color(0, 0, 0));
        trainersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Bebidas", "Agua", "200",  new Double(2000.0)},
                {"Bebidas", "Powerade", "100",  new Double(2700.0)}
            },
            new String [] {
                "Tipo", "Nombre", "Cantidad", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        trainersTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        trainersTable.setFocusable(false);
        trainersTable.setGridColor(new java.awt.Color(128, 128, 128));
        trainersTable.setRowHeight(25);
        trainersTable.setSelectionBackground(new java.awt.Color(254, 205, 77));
        jScrollPane1.setViewportView(trainersTable);

        btnUpdateTrainer.setBackground(new java.awt.Color(254, 205, 77));
        btnUpdateTrainer.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        btnUpdateTrainer.setForeground(new java.awt.Color(0, 0, 0));
        btnUpdateTrainer.setText("Editar");
        btnUpdateTrainer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdateTrainer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateTrainerActionPerformed(evt);
            }
        });

        btnDeleteTrainer.setBackground(new java.awt.Color(254, 205, 77));
        btnDeleteTrainer.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        btnDeleteTrainer.setForeground(new java.awt.Color(0, 0, 0));
        btnDeleteTrainer.setText("Eliminar");
        btnDeleteTrainer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeleteTrainer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteTrainerActionPerformed(evt);
            }
        });

        btnRegisterTrainer.setBackground(new java.awt.Color(254, 205, 77));
        btnRegisterTrainer.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        btnRegisterTrainer.setForeground(new java.awt.Color(0, 0, 0));
        btnRegisterTrainer.setText("Nuevo");
        btnRegisterTrainer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegisterTrainer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterTrainerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(jLabel1)
                        .addGap(30, 30, 30)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1)
                            .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(btnRegisterTrainer, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(200, 200, 200)
                        .addComponent(btnUpdateTrainer, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(200, 200, 200)
                        .addComponent(btnDeleteTrainer, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1028, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(383, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateTrainer)
                    .addComponent(btnDeleteTrainer)
                    .addComponent(btnRegisterTrainer))
                .addContainerGap(246, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFilterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFilterKeyReleased
        filter();
    }//GEN-LAST:event_txtFilterKeyReleased

    private void btnUpdateTrainerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateTrainerActionPerformed
        int selection = trainersTable.getSelectedRow();

        if (selection < 0) {
            JOptionPane.showMessageDialog(null, "Seleccione un entrenador antes de continuar", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String cedula = trainersTable.getValueAt(selection, 0).toString();
        Trainer trainer = controller.selectTrainer(cedula);

        if (trainer != null) {
            view.openUpdateTrainerView(this, trainer);
        }

    }//GEN-LAST:event_btnUpdateTrainerActionPerformed

    private void btnDeleteTrainerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteTrainerActionPerformed
        int selection = trainersTable.getSelectedRow();

        if (selection < 0) {
            JOptionPane.showMessageDialog(null, "Seleccione un entrenador antes de continuar", "Advertencia", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String cedula = trainersTable.getValueAt(selection, 0).toString();

        int answer = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar el entrenador?", "Advertencia", JOptionPane.YES_NO_OPTION);

        if (answer == 0) {
            controller.deleteTrainer(cedula);
            JOptionPane.showMessageDialog(null, "Entrenador eliminado correctamente");
            fillTrainersTable();
        }
    }//GEN-LAST:event_btnDeleteTrainerActionPerformed

    private void btnRegisterTrainerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterTrainerActionPerformed
        view.openRegisterTrainerView(this);
    }//GEN-LAST:event_btnRegisterTrainerActionPerformed

    private void mainPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainPanelMouseClicked
        trainersTable.clearSelection();
        
    }//GEN-LAST:event_mainPanelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteTrainer;
    private javax.swing.JButton btnRegisterTrainer;
    private javax.swing.JButton btnUpdateTrainer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTable trainersTable;
    private javax.swing.JTextField txtFilter;
    // End of variables declaration//GEN-END:variables
}
